export const PYODIDE_CONFIG = {
  VERSION: "v0.27.7",
  CDN_BASE_URL: "https://cdn.jsdelivr.net/pyodide",
  PERSIST_ROOT: "/persist",
  STORAGE_VERSION_KEY: "pyodide_storage_version",
  CURRENT_STORAGE_VERSION: "4.0.0",
  API_PATHS: [
    "/persist/api",
    "/persist/api/app",
    "/persist/api/app/api",
    "/persist/api/app/api/v1",
    "/persist/api/app/core",
    "/persist/api/app/db",
    "/persist/api/app/domains",
    "/persist/api/app/domains/todos",
  ],
  API_FILES: [
    "/__init__.py",
    "/app/__init__.py",
    "/app/app_main.py",
    "/app/api/__init__.py",
    "/app/api/v1/__init__.py",
    "/app/core/asgi_server.py",
    "/app/core/settings.py",
    "/app/core/logging.py",
    "/app/core/security.py",
    "/app/core/runtime.py",
    "/app/core/deps.py",
    "/app/core/__init__.py",
    "/app/db/base.py",
    "/app/db/session.py",
    "/app/db/init_db.py",
    "/app/db/__init__.py",
    "/app/domains/todos/models.py",
    "/app/domains/todos/schemas.py",
    "/app/domains/todos/router.py",
    "/app/domains/todos/service.py",
    "/app/domains/todos/__init__.py",
    "/app/domains/__init__.py",
    "/app/domains/models.py",
  ],
  MUTATING_METHODS: ["POST", "PUT", "PATCH", "DELETE"],
  REQUIRED_PACKAGES: ["fastapi", "pydantic", "sqlalchemy", "typing_extensions"],
} as const;
