export const PYODIDE_CONFIG = {
  VERSION: "v0.27.7",
  CDN_BASE_URL: "https://cdn.jsdelivr.net/pyodide",
  PERSIST_ROOT: "/persist",
  STORAGE_VERSION_KEY: "pyodide_storage_version",
  CURRENT_STORAGE_VERSION: "1.0.0",
  API_PATHS: [
    "/persist/api",
    "/persist/api/app",
    "/persist/api/app/api",
    "/persist/api/app/api/v1",
    "/persist/api/app/core",
    "/persist/api/app/db",
    "/persist/api/app/domains",
    "/persist/api/app/domains/users",
    "/persist/api/app/domains/posts",
    "/persist/api/app/domains/dashboard",
    "/persist/api/app/domains/system",
    "/persist/api/v1",
  ],
  API_FILES: [
    "/__init__.py",
    "/app/__init__.py",
    "/app/app_main.py",
    "/app/api/__init__.py",
    "/app/api/v1/__init__.py",
    "/app/core/bridge.py",
    "/app/core/settings.py",
    "/app/core/logging.py",
    "/app/core/security.py",
    "/app/core/runtime.py",
    "/app/core/deps.py",
    "/app/core/__init__.py",
    "/app/db/base.py",
    "/app/db/session.py",
    "/app/db/init_db.py",
    "/app/db/__init__.py",
    "/app/domains/users/models.py",
    "/app/domains/users/schemas.py",
    "/app/domains/users/router.py",
    "/app/domains/users/service.py",
    "/app/domains/users/__init__.py",
    "/app/domains/posts/models.py",
    "/app/domains/posts/schemas.py",
    "/app/domains/posts/router.py",
    "/app/domains/posts/service.py",
    "/app/domains/posts/__init__.py",
    "/app/domains/dashboard/router.py",
    "/app/domains/dashboard/__init__.py",
    "/app/domains/system/router.py",
    "/app/domains/system/__init__.py",
    "/app/domains/__init__.py",
    "/v1/main.py",
  ],
  MUTATING_METHODS: ["POST", "PUT", "PATCH", "DELETE"],
  REQUIRED_PACKAGES: ["fastapi", "pydantic", "sqlalchemy", "typing_extensions"],
} as const;
