export const PYODIDE_CONFIG = {
  VERSION: "v0.27.7",
  CDN_BASE_URL: "https://cdn.jsdelivr.net/pyodide",
  PERSIST_ROOT: "/persist",
  STORAGE_VERSION_KEY: "pyodide_storage_version",
  CURRENT_STORAGE_VERSION: "1.0.0",
  API_PATHS: [
    "/persist/api",
    "/persist/api/v1",
    "/persist/api/models",
    "/persist/api/schemas",
    "/persist/api/database",
  ],
  API_FILES: [
    "/__init__.py",
    "/bridge.py",
    "/database/__init__.py",
    "/database/connection.py",
    "/models/__init__.py",
    "/models/models.py",
    "/schemas/__init__.py",
    "/schemas/schemas.py",
    "/utils.py",
    "/v1/__init__.py",
    "/v1/main.py",
  ],
  MUTATING_METHODS: ["POST", "PUT", "PATCH", "DELETE"],
  REQUIRED_PACKAGES: ["fastapi", "pydantic", "sqlalchemy", "typing_extensions"],
} as const;
