[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyodide-bridge-py"
version = "0.1.0"
description = "FastAPI bridge for Pyodide environments"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "React FastAPI Pyodide", email = "contact@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.100.0",
    "pydantic>=2.0",
]

[project.scripts]
pyodide-bridge = "pyodide_bridge.cli.main:main"
pyodide-bridge-add-operation-ids = "pyodide_bridge.cli.main:add_operation_ids_command"
pyodide-bridge-validate-operation-ids = "pyodide_bridge.cli.main:validate_operation_ids_command"
pyodide-bridge-generate-pages = "pyodide_bridge.cli.generate_pages:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0",
    "isort>=5.0",
    "mypy>=1.0",
]

[project.urls]
Homepage = "https://github.com/your-repo/react-fastapi-pyodide"
Repository = "https://github.com/your-repo/react-fastapi-pyodide"
Issues = "https://github.com/your-repo/react-fastapi-pyodide/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
strict = true